project:
  type: website

website:
  favicon: assets/images/logo ifremer RVB.png
  page-navigation: true
  bread-crumbs: true
  page-footer:
    left: |
      Proudly supported by OSC
    center:
      - icon: gitlab
        href: https://gitlab.ifremer.fr/osc/documentation/osc-web
        aria-label: osc-web GitLab
        text: Source Code
  navbar:
    pinned: true
    logo: assets/images/logo ifremer RVB.png
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: docs/Documentations/documentationshome.qmd
        text: Documentations
      - href: docs/Tutorials/tutorialshome.qmd
        text: Tutorials
  sidebar:
    - id: Tutorials
      title: "Tutorials"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - docs/Tutorials/tutorialshome.qmd
        - text: "Tutorial: Publish Jupyter notebook"
          href: docs/Tutorials/jupyternotebook.qmd
        - text: "Tutorial: Publish Quarto book"
          href: docs/Tutorials/quartobook.qmd
    - id: Documentations
      title: "Documentations"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - docs/Documentations/documentationshome.qmd

  announcement:
    icon: info-circle
    dismissable: true
    content: "**Note** - This website is in development"
    type: warning
    position: above-navbar

format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: assets/css/styles.css
    toc: true


