project:
  type: website

website:
  favicon: assets/images/Argo_logo_tallspacer.png
  page-navigation: true
  bread-crumbs: true
  page-footer:
    left: |
      Argo data management
    center:
      - icon: gitlab
        href: https://gitlab.ifremer.fr/coriolis/argodatamgt
        aria-label: Argo data management web GitLab
        text: Source Code
  navbar:
    pinned: true
    logo: assets/images/Argo_logo_tallspacer.png
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: docs/News/News.qmd
        text: News
      - href: docs/DataAccess.qmd
        text: Data
      - href: docs/Documentation.qmd
        text: Documentation
      - href: docs/DataManagementTeam.qmd
        text: ADMT
      - href: docs/Dmqc.qmd
        text: DMQC
      - href: docs/ArgoVocabulary.qmd
        text: Vocabularies
      - href: docs/Monitoring.qmd
        text: Monitoring

format:
  html:
    theme:
        light: yeti
        dark: darkly
    css: assets/css/styles.css
    toc: true

resources:
  - "assets/json/*.json"        # Inclut tout le répertoire 'data' (fichiers et sous-répertoires)

