project:
  type: website

website:
  page-navigation: true
  bread-crumbs: true
  navbar:
    pinned: true
    logo: assets/images/quartologo.png
    collapse-below: lg
    tools:
      - icon: gitlab
        menu:
          - text: Source Code
            href: https://gitlab.ifremer.fr/cp7b596/quartoweb-test
          - text: Report an Issue
            href: https://gitlab.ifremer.fr/cp7b596/quartoweb-test/-/issues
    left:
      - href: index.qmd
        text: Home
      - href: docs/Documentations/documentationshome.qmd
        text: Documentations
      - href: docs/Tutorials/tutorialshome.qmd
        text: Tutorials
  sidebar:
    - id: Tutorials
      title: "Tutorials"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - docs/Tutorials/tutorialshome.qmd
        - text: "Tutorial: Publish Jupyter notebook"
          href: docs/Tutorials/jupyternotebook.qmd
        - text: "Tutorial: Publish Quarto book"
          href: docs/Tutorials/quartobook.qmd
    - id: Documentations
      title: "Documentations"
      style: "floating"
      collapse-level: 1
      align: left
      contents:
        - docs/Documentations/documentationshome.qmd

  announcement:
    icon: info-circle
    dismissable: true
    content: "**Note** - This website is in development"
    type: warning
    position: below-navbar

format:
  html:
    theme: flatly
    css: assets/css/styles.css
    toc: true

