project:
  type: website

website:
  favicon: assets/images/Argo_logo_tallspacer.png
  page-navigation: true
  bread-crumbs: true
  page-footer:
    left: |
      Argo data management
    center:
      - icon: gitlab
        href: https://gitlab.ifremer.fr/coriolis/argodatamgt
        aria-label: Argo data management web GitLab
        text: Source Code
  navbar:
    pinned: true
    logo: assets/images/Argo_logo_tallspacer.png
    collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      - href: docs/News/News.qmd
        text: News
      - href: docs/DataAccess/DataAccess.qmd
        text: Data access
      - href: docs/Documentation/Documentation.qmd
        text: Documentation
      - href: docs/DataManagementTeam/DataManagementTeam.qmd
        text: Data management team

  announcement:
    icon: info-circle
    dismissable: true
    content: "**Note** - will soon replace http://www.argodatamgt.org"
    type: warning
    position: above-navbar

format:
  html:
    theme:
        light: yeti
        dark: darkly
    css: assets/css/styles.css
    toc: true


