---
title: "Documentation"
---

# How is Argo data management organized ?  
- [A beginners' guide to accessing Argo data](https://argo.ucsd.edu/data/how-to-use-argo-files/){target="_blank"}
- [Argo data FAQ](https://argo.ucsd.edu/data/data-faq/){target="_blank"}

# Argo data formats
- The Argo data formats are described in the "Argo user's manual" [https://dx.doi.org/10.13155/29825](https://dx.doi.org/10.13155/29825){target="_blank"}
- Argo user manual for technical files
  - [Technical parameters naming convention rules](https://github.com/OneArgo/argo-format-user-manual/blob/7bb1777ecaa00e2f3364956faa0faab4fd6eff21/etc/Technical_Naming_Convention_rules_V4.doc){target="_blank"}
  - [Technical and configuration parameters units](https://github.com/OneArgo/argo-format-user-manual/blob/d1ab29664f9e94d291c002099accd34cb27f8f2c/etc/Table%20Tech%20and%20Conf%20Units.xlsx){target="_blank"}
- Argo metadata files
  - [Configuration parameter names, core-Argo](https://github.com/OneArgo/argo-format-user-manual/blob/d1ab29664f9e94d291c002099accd34cb27f8f2c/etc/Core_Argo_ConfigurationParameterNames.xlsx){target="_blank"}
  - [Configuration parameter names, BGC-Argo](https://github.com/OneArgo/argo-format-user-manual/blob/d1ab29664f9e94d291c002099accd34cb27f8f2c/etc/Bio_Argo_Configuration_Parameter_Names.xlsx){target="_blank"}
- [Surface pressure correction table](https://github.com/OneArgo/argo-format-user-manual/blob/d1ab29664f9e94d291c002099accd34cb27f8f2c/etc/SurfacePressureCorrectionTable.xls){target="_blank"}

# Quality control
- Argo quality control manual for CTD and trajectory data [https://dx.doi.org/10.13155/33951](https://dx.doi.org/10.13155/33951){target="_blank"}
- Argo quality control manual for dissolved oxygen concentration [https://doi.org/10.13155/46542](https://doi.org/10.13155/46542){target="_blank"}
- BGC-Argo quality control manual for biogeochemical data [https://dx.doi.org/10.13155/40879](https://dx.doi.org/10.13155/40879){target="_blank"}
- BGC-Argo quality control manual for chlorophyll-A concentration [https://dx.doi.org/10.13155/35385](https://dx.doi.org/10.13155/35385){target="_blank"}
- BGC-Argo quality control manual for nitrate concentration [https://doi.org/10.13155/84370](https://doi.org/10.13155/84370){target="_blank"}
- BGC-Argo quality control for radiometry [https://doi.org/10.13155/62466](https://doi.org/10.13155/62466){target="_blank"}
- BGC-Argo quality control manual for pH [https://doi.org/10.13155/97828](https://doi.org/10.13155/97828){target="_blank"}
- BGC Argo quality control manual for particles backscattering [https://doi.org/10.13155/60262](https://doi.org/10.13155/60262){target="_blank"}

# Cookbooks, Core-Argo
- Argo DAC profile cookbook [https://dx.doi.org/10.13155/41151](https://dx.doi.org/10.13155/41151){target="_blank"}
- Argo DAC trajectory cookbook [https://dx.doi.org/10.13155/29824](https://dx.doi.org/10.13155/29824){target="_blank"}
- [Common method for determining position and Time and attribute the appropriate QC](https://github.com/OneArgo/argo-format-user-manual/blob/ae417bbbe9806b80637b9d7d9824f2484986228d/etc/Method-Position-Time-QC.pdf){target="_blank"}
- Core-Argo DMQC cookbook [https://doi.org/10.13155/78994](https://doi.org/10.13155/78994){target="_blank"}
 
# Cookbooks, BGC-Argo
- Processing Argo oxygen data at the DAC level cookbook [https://doi.org/10.13155/39795](https://doi.org/10.13155/39795){target="_blank"}
- BGC-Argo processing particle backscattering at the DAC level [https://dx.doi.org/10.13155/39459](https://dx.doi.org/10.13155/39459){target="_blank"}
- BGC-Argo processing chlorophyll-A concentration at the DAC level [https://dx.doi.org/10.13155/39468](https://dx.doi.org/10.13155/39468){target="_blank"}
- BGC-Argo processing Argo measurement timing information at the DAC level [https://dx.doi.org/10.13155/47998](https://dx.doi.org/10.13155/47998){target="_blank"}
- Processing BGC-Argo CDOM concentration at the DAC level [https://doi.org/10.13155/54541](https://doi.org/10.13155/54541){target="_blank"}
- Processing Bio-Argo nitrate concentration at the DAC Level [https://dx.doi.org/10.13155/46121](https://dx.doi.org/10.13155/46121){target="_blank"}
- Processing BGC-Argo Radiometric data at the DAC level [https://doi.org/10.13155/51541](https://doi.org/10.13155/51541){target="_blank"}
- Processing BGC-Argo pH data at the DAC level [https://doi.org/10.13155/57195](https://doi.org/10.13155/57195){target="_blank"}

# Cookbooks, GDAC
- Description of the Argo GDAC File Checks: Data Format and Consistency Checks [https://dx.doi.org/10.13155/46120](https://dx.doi.org/10.13155/46120){target="_blank"}
- BGC-Argo synthetic profile file processing and format on Coriolis GDAC [https://doi.org/10.13155/55637](https://doi.org/10.13155/55637){target="_blank"}
- Argo GDAC cookbook [https://doi.org/10.13155/46202](https://doi.org/10.13155/46202){target="_blank"}

