---
title: "Documentation"
---

# How is Argo data management organized ?  
- [A beginners' guide to accessing Argo data](https://argo.ucsd.edu/data/how-to-use-argo-files/)
- [Argo data FAQ](https://argo.ucsd.edu/data/data-faq/)

# Argo data formats
- The Argo data formats are described in the "Argo user's manual" [https://dx.doi.org/10.13155/29825](https://dx.doi.org/10.13155/29825)
- Argo physical parameters list: core-Argo and BGC-Argo
- Argo user manual for technical files
-- Technical parameters names
-- Technical parameters naming convention rules
-- Technical and configuration parameters units
- Argo metadata files
-- Configuration parameter names, core-Argo
-- Configuration parameter names, BGC-Argo
-- Surface pressure correction table

# Quality control
- Argo quality control manual for CTD and trajectory data [https://dx.doi.org/10.13155/33951](https://dx.doi.org/10.13155/33951)
- Argo quality control manual for dissolved oxygen concentration [https://doi.org/10.13155/46542](https://doi.org/10.13155/46542)
- BGC-Argo quality control manual for biogeochemical data [https://dx.doi.org/10.13155/40879](https://dx.doi.org/10.13155/40879)
- BGC-Argo quality control manual for chlorophyll-A concentration [https://dx.doi.org/10.13155/35385](https://dx.doi.org/10.13155/35385)
- BGC-Argo quality control manual for nitrate concentration [https://doi.org/10.13155/84370](https://doi.org/10.13155/84370)
- BGC-Argo quality control for radiometry [https://doi.org/10.13155/62466](https://doi.org/10.13155/62466)
- BGC-Argo quality control manual for pH [https://doi.org/10.13155/97828](https://doi.org/10.13155/97828) 
- BGC Argo quality control manual for particles backscattering [https://doi.org/10.13155/60262](https://doi.org/10.13155/60262) 

# Cookbooks, Core-Argo
- Argo DAC profile cookbook [https://dx.doi.org/10.13155/41151](https://dx.doi.org/10.13155/41151)
- Argo DAC trajectory cookbook [https://dx.doi.org/10.13155/29824](https://dx.doi.org/10.13155/29824)
-Common method for determining position and Time and attribute the appropriate QC
-Core-Argo DMQC cookbook [https://doi.org/10.13155/78994](https://doi.org/10.13155/78994)
 
# Cookbooks, BGC-Argo
- Processing Argo oxygen data at the DAC level cookbook [https://doi.org/10.13155/39795](https://doi.org/10.13155/39795)
- BGC-Argo processing particle backscattering at the DAC level [https://dx.doi.org/10.13155/39459](https://dx.doi.org/10.13155/39459)
- BGC-Argo processing chlorophyll-A concentration at the DAC level [https://dx.doi.org/10.13155/39468](https://dx.doi.org/10.13155/39468)
- BGC-Argo processing Argo measurement timing information at the DAC level [https://dx.doi.org/10.13155/47998](https://dx.doi.org/10.13155/47998)
- Processing BGC-Argo CDOM concentration at the DAC level [https://doi.org/10.13155/54541](https://doi.org/10.13155/54541)
- Processing Bio-Argo nitrate concentration at the DAC Level [https://dx.doi.org/10.13155/46121](https://dx.doi.org/10.13155/46121)
- Processing BGC-Argo Radiometric data at the DAC level [https://doi.org/10.13155/51541](https://doi.org/10.13155/51541)
- Processing BGC-Argo pH data at the DAC level [https://doi.org/10.13155/57195](https://doi.org/10.13155/57195)

# Cookbooks, GDAC
- Description of the Argo GDAC File Checks: Data Format and Consistency Checks [https://dx.doi.org/10.13155/46120](https://dx.doi.org/10.13155/46120)
- Description of the Argo GDAC BGC File Merge Process [https://dx.doi.org/10.13155/52154](https://dx.doi.org/10.13155/52154)
- BGC-Argo synthetic profile file processing and format on Coriolis GDAC [https://doi.org/10.13155/55637](https://doi.org/10.13155/55637)
- Argo GDAC cookbook [https://doi.org/10.13155/46202](https://doi.org/10.13155/46202)

