---
title: "Data access"
---
## Argo data sources
There are many sources of Argo data depending on the desired format, source and application.
A complete presentation is available on [https://argo.ucsd.edu/data](https://argo.ucsd.edu/data){target="_blank"}

## Ftp, https, s3 data services
Argo data are freely available from US-Godae and Coriolis GDAC sites with ftp, https or s3 protocols.

- [ftp://ftp.ifremer.fr/ifremer/argo](ftp://ftp.ifremer.fr/ifremer/argo){target="_blank"}
- [https://data-argo.ifremer.fr](https://data-argo.ifremer.fr){target="_blank"} / [https://usgodae.org/pub/outgoing/argo](https://nrlgodae1.nrlmry.navy.mil/pub/outgoing/argo){target="_blank"}
- s3: Argo data are updated daily on [https://registry.opendata.aws/argo-gdac-marinedata](https://registry.opendata.aws/argo-gdac-marinedata){target="_blank"}

## Argo DOI, Digital Object Identifier
A digital object identifier (DOI) is a unique identifier for an electronic document or a dataset.  
Argo data-management assigns DOIs to its documents and datasets for two main objectives:

- Citation: in a publication the DOI is efficiently tracked by bibliographic surveys
- Traceability: the DOI is a direct and permanent link to the document or data set used in a publication

Argo floats data and metadata from Global Data Assembly Centre (Argo GDAC)

- [https://doi.org/10.17882/42182](https://doi.org/10.17882/42182){target="_blank"}

## Data format
Argo data, metadata, technical data are managed in NetCDF files.  
The index files list and provide a short description the NetCDF files content. The index files format is ASCII "csv" (comma separated values).  
The description of the Argo formats, the file naming conventions and more are documented in 

- Argo user's manual: [https://dx.doi.org/10.13155/29825](https://dx.doi.org/10.13155/29825){target="_blank"}

## Organization
GDACs are continuously updated in real-time and delayed mode with data from Data Assembly Centers (DACs).
The Argo GDAC dataset provides 3 "views" of the data profiles:

- DAC: a directory per data assembly center / a directory per profiler / a file per profile
- GEO: a directory per ocean / a directory per year in the ocean / a directory per month of the year / a directory per day of the month / a file per profile of the day
- LATEST_DATA: a directory per year / a directory per month of the year / a directory per day of the month / a file per profile of the day

## Argo data selection
Argo Data Selection is a web interface to discover, select and subset Argo data. Your selection can be downloaded as NetCDF or CSV files.

- [https://dataselection.euro-argo.eu](https://dataselection.euro-argo.eu){target="_blank"}

## Argo floats dashboard
Argo Floats Dashboard is a web interface to discover Argo floats with metadata, maps, graphics and technical alerts.

- [https://fleetmonitoring.euro-argo.eu/dashboard](https://fleetmonitoring.euro-argo.eu/dashboard){target="_blank"}

## Argo synchronization service
The synchronization service is available from Ifremer "rsync" and from "aws s3 sync".
From the user side, the synchronization service:

- Downloads the new files
- Downloads the updated files
- Removes the files that have been removed from the GDAC
- Compresses/uncompresses the files during the transfer
- Preserves the files creation/update dates
- Lists all the files that have been transferred (easy to use for a user side post-processing)

### Ifremer rsync
The rsync server "vdmzrs.ifremer.fr" provides a synchronization service between the "dac" directory of the GDAC with a user mirror. The "dac" index files are available from "argo-index".

#### Examples
Synchronization of a particular float, based on the data centre in charge of data processing:

- rsync -avzh \-\-delete vdmzrs.ifremer.fr::argo/coriolis/69001 mydirectory
- rsync -avzh \-\-delete vdmzrs.ifremer.fr::argo/aoml/1900050 mydirectory
- rsync -avzh \-\-delete vdmzrs.ifremer.fr::argo-index/ mydirectory
- Synchronization of the whole dac directory of Argo GDAC
  - rsync -avzh \-\-delete vdmzrs.ifremer.fr::argo/ mydirectory

### aws s3 sync
The aws s3 sync command allows you to synchronize the content of a local directory with the GDAC Argo S3 bucket, copying only new or modified files.

#### Examples
- aws s3 sync \-\-no-sign-request s3://argo-gdac-sandbox/pub/dac/coriolis/6902833 mydirectory
- aws s3 sync \-\-no-sign-request s3://argo-gdac-sandbox/pub/aux/coriolis/6902833 mydirectory
- aws s3 sync \-\-no-sign-request s3://argo-gdac-sandbox/pub/idx mydirectory


## Erddap data server
Erddap is NOAA’s data server to scientific data
Erddap is a data server that gives you a simple, consistent way to download subsets of scientific datasets in common file formats and make graphs and maps. This particular Erddap installation has oceanographic data (for example, data from Argo floats, satellites and buoys).

- [https://erddap.ifremer.fr/erddap/tabledap/ArgoFloats.html](https://erddap.ifremer.fr/erddap/tabledap/ArgoFloats.html){target="_blank"}

## Thredds data server
Unidata's Thredds Data Server (TDS) is a web server that provides metadata and data access for scientific datasets, using OPeNDAP, OGC WMS, WCS, HTTP protocols.

- [https://tds0.ifremer.fr/thredds/catalog/CORIOLIS-ARGO-GDAC-OBS/catalog.html](https://tds0.ifremer.fr/thredds/catalog/CORIOLIS-ARGO-GDAC-OBS/catalog.html){target="_blank"}
